### PR TITLE
Quick clean-up

### PR DESCRIPTION
**Pull request by mikestone14**
- Removes test-unit test files
- Removes unused actions in controller
- Fixes indentation in models
- Removes views
- Removes empty space in routes file

### CODE REVIEW

**Comment by mikestone14** [comment]
Do you have Sublime tabs as 2 spaces or 4? I'm thinking that might be why the indentation was off.

**Comment by jhenley45** [comment]
I think 2 but I can check

**Comment by jhenley45** [comment]
Indentation is 2. I've had this problem in the past where the indentation in my files was huge after pulling someone else's code. Don't know how to fix it, just had to bite the bullet. Would hate to see Foodiest fail because of indentation...

"So Mike, why did your last venture fizzle out?"

**Comment by mikestone14** [comment]
:no_good:

**Comment by jhenley45** [comment]
Sorry what was the point of moving all of the controller actions? We'll still need those to interact with ember.

**Comment by mikestone14** [comment]
I removed them because we're not using them so we don't have unused actions. We might want to remove the routes too until we know what we're doing. Maybe it's worth another sit down session soon to talk about next steps?

**Comment by jhenley45** [comment]
Surely we can do that sometime soon.

I don't know why we wouldn't use these actions and the route as well
though. Rails is acting as our API so it will still have to route and
handle request, they'll just all be JSON requests. I just assumed when I
set up the controllers that we would need basic CRUD functionality for most
of the models.

**Comment by mikestone14** [comment]
Yeah totally and I'm sure you're right that we will use the routes and actions at some point but we're not really sure yet and we might use some or most but not all. I don't know, it's just really easy to add routes and controller actions when we decide we want to build something so we might as well do it as part of those features.

**Comment by mikestone14** [comment]
Speaking of Ember, do you want to add the models? I guess I could but I know you're the Ember guru.

**Comment by jhenley45** [comment]
OK I'm cool with that, will merge this in.

We can add the ember models in whenever, if you want to do that it might be good practice. I was actually thinking of starting in on user authentication next. We use ember simple auth in our app (https://github.com/simplabs/ember-simple-auth) which is nice. I'm assuming we're planning on using Devise for the rails authentication, and sure enough there is a simple-auth-devise gem (https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-devise). I was just reading up on that and may start in on it tonight. Other option would be to roll our own authentication which I've never done. Don't need to re-invent the wheel but it could be a fun exercise. There's a nice railscast on it (http://railscasts.com/episodes/250-authentication-from-scratch).

Thoughts?

**Pull request merged**
